CREATE TABLE "PROPRIO" (
    IDP NUMBER(6),
    NOM VARCHAR2(20),
    PRENOM VARCHAR2(20),
    CONSTRAINT PK_PROPRIO PRIMARY KEY (IDP)
);

CREATE TABLE ESPACE (
    IDE NUMBER(6),
    DESIGNATION VARCHAR2(30),
    SUPERFICIE NUMBER(7,2),
    IDERATTACH NUMBER(6),   
    
    CONSTRAINT PK_IDE PRIMARY KEY (IDE),
    CONSTRAINT FK_IDERATTACH FOREIGN KEY (IDERATTACH) REFERENCES ESPACE (IDE) 
); 

CREATE TABLE BIEN (
IDEBIEN NUMBER(6),
CATEGORIE VARCHAR(20), 
TYPE VARCHAR(20),
IDP NUMBER(6),
VILLE VARCHAR(20),
PRIX NUMBER(10, 2),
CONSTRAINT PK_BIEN PRIMARY KEY(IDEBIEN),
CONSTRAINT FK_BIEN FOREIGN KEY(IDEBIEN) REFERENCES ESPACE(IDE),
CONSTRAINT FK_BIEN2 FOREIGN KEY(IDP) REFERENCES PROPRIO(IDP)
);


INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (1,'PENPLU','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (2,'BON','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (3,'RACINE','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (4,'BONBEUR','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (5,'GONZOLA','IGOR');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (105,'REPARATEURINFORMATIC','GONALIN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (7,'LELOMBRIC','GUERIC');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (8,'TIME','VINCENT');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (9,'MALOU','EDDY');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (10,'LOEB','SEBASTIEN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (11,'ESTRE','KEVIN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (12,'BLOCK','KEN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (13,'AURIOL','DIDIER');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (14,'OGIER','SEBASTIEN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (15,'MOUTON','MICHEL');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (16,'PROST','ALAIN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (17,'ARNOUX','RENE');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (18,'BI','CESAR');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (19,'DISWAR','SAM');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (20,'AFEELING','AGATHE');

INSERT INTO BIEN VALUES (10, 'APPARTEMENT', 'STUDIO', 1, 'MARSEILLE', 12000);
INSERT INTO BIEN VALUES (20, 'APPARTEMENT', 'T2', 2, 'PARIS', 15000);
INSERT INTO BIEN VALUES (30, 'MAISON DE VILLE', 'T3', 3, 'AIX-EN-PROVENCE', 125000);
INSERT INTO BIEN VALUES (40, 'MAISON DE VILLE', 'T2', 4, 'LYON', 110000);
INSERT INTO BIEN VALUES (50, 'VILLA', 'JUMELLEES', 5, 'LILE', 350000);
INSERT INTO BIEN VALUES (60, 'VILLA', 'MITOYENNE', 6, 'AIX-EN-PROVENCE', 250000);
INSERT INTO BIEN VALUES (70, 'APPARTEMENT', 'T3', 7, 'LYON', 15000);
INSERT INTO BIEN VALUES (80, 'APPARTEMENT', 'STUDIO', 8, 'PARIS', 13000);
INSERT INTO BIEN VALUES (90, 'VILLA', 'JUMELLEES', 9, 'LYON', 325000);
INSERT INTO BIEN VALUES (100, 'APPARTEMENT', 'STUDIO', 105, 'MARSEILLE', 12000);
INSERT INTO BIEN VALUES (110, 'VILLA', 'MITOYENNE', 11, 'PARIS', 300000);
INSERT INTO BIEN VALUES (120, 'MAISON DE VILLE', 'T3', 12, 'LYON', 120000);
INSERT INTO BIEN VALUES (130, 'APPARTEMENT', 'T2', 13, 'SALON', 10000);
INSERT INTO BIEN VALUES (945, 'VILLA', 'MITOYENNE', 14, 'AIX-EN-PROVENCE', 250000);
INSERT INTO BIEN VALUES (150, 'VILLA', 'MITOYENNE', 15, 'LILE', 150000);
INSERT INTO BIEN VALUES (160, 'MAISON DE VILLE','T2', 16, 'MARSEILLE', 100000);
INSERT INTO BIEN VALUES (170, 'MAISON DE VILLE', 'T3', 17, 'LILE', 123000);
INSERT INTO BIEN VALUES (180, 'APPARTEMENT', 'STUDIO', 18, 'MARSEILLE', 12000);
INSERT INTO BIEN VALUES (190, 'MAISON DE VILLE', 'T3', 19, 'AIX-EN-PROVENCE', 125000);
INSERT INTO BIEN VALUES (200, 'APPARTEMENT', 'STUDIO', 20, 'LILE', 13000);