CREATE TABLE "PROPRIO" (
    IDP NUMBER(6),
    NOM VARCHAR2(20),
    PRENOM VARCHAR2(20),
    CONSTRAINT PK_PROPRIO PRIMARY KEY (IDP)
);


INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (1,'PENPLU','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (2,'BON','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (3,'RACINE','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (4,'BONBEUR','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (5,'GONZOLA','IGOR');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (6,'REPARATEURINFORMATIC','GONALIN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (7,'LELOMBRIC','GUERIC');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (8,'TIME','VINCENT');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (9,'MALOU','EDDY');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (10,'LOEB','SEBASTIEN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (11,'ESTRE','KEVIN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (12,'BLOCK','KEN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (13,'AURIOL','DIDIER');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (14,'OGIER','SEBASTIEN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (15,'MOUTON','MICHEL');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (16,'PROST','ALAIN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (17,'ARNOUX','RENE');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (18,'BI','CESAR');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (19,'DISWAR','SAM');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (20,'AFEELING','AGATHE');