/*----------------------------------------------------------------------------*/
/*////////////////////////////////// PRORIO //////////////////////////////////*/
/*----------------------------------------------------------------------------*/

INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (1,'PENPLU','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (2,'BON','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (3,'RACINE','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (4,'BONBEUR','JEAN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (5,'GONZOLA','IGOR');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (105,'REPARATEURINFORMATIC','GONALIN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (7,'LELOMBRIC','GUERIC');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (8,'TIME','VINCENT');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (9,'MALOU','EDDY');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (10,'LOEB','SEBASTIEN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (11,'ESTRE','KEVIN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (12,'BLOCK','KEN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (13,'AURIOL','DIDIER');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (14,'OGIER','SEBASTIEN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (15,'MOUTON','MICHEL');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (16,'PROST','ALAIN');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (17,'ARNOUX','RENE');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (18,'BI','CESAR');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (19,'DISWAR','SAM');
INSERT INTO PROPRIO (IDP, NOM, PRENOM) VALUES (20,'AFEELING','AGATHE');

/*----------------------------------------------------------------------------*/
/*/////////////////////////////////// BIEN ///////////////////////////////////*/
/*----------------------------------------------------------------------------*/
/* DO THE CORRESPONDING ESPACE TUBLE */
INSERT INTO BIEN VALUES (10, 'APPARTEMENT', 'STUDIO', 1, 'MARSEILLE', 12000);
INSERT INTO BIEN VALUES (20, 'APPARTEMENT', 'T2', 2, 'PARIS', 15000);
INSERT INTO BIEN VALUES (30, 'MAISON DE VILLE', 'T3', 3, 'AIX-EN-PROVENCE', 125000);
INSERT INTO BIEN VALUES (40, 'MAISON DE VILLE', 'T2', 4, 'LYON', 110000);
INSERT INTO BIEN VALUES (50, 'VILLA', 'JUMELLEES', 5, 'LILE', 350000);
INSERT INTO BIEN VALUES (60, 'VILLA', 'MITOYENNE', 6, 'AIX-EN-PROVENCE', 250000);
INSERT INTO BIEN VALUES (70, 'APPARTEMENT', 'T3', 7, 'LYON', 15000);
INSERT INTO BIEN VALUES (80, 'APPARTEMENT', 'STUDIO', 8, 'PARIS', 13000);
INSERT INTO BIEN VALUES (90, 'VILLA', 'JUMELLEES', 9, 'LYON', 325000);
INSERT INTO BIEN VALUES (100, 'APPARTEMENT', 'STUDIO', 105, 'MARSEILLE', 12000);
INSERT INTO BIEN VALUES (110, 'VILLA', 'MITOYENNE', 11, 'PARIS', 300000);
/*----------------------------------------------------------------------------*/
INSERT INTO BIEN VALUES (120, 'MAISON DE VILLE', 'T3', 12, 'LYON', 120000);
INSERT INTO BIEN VALUES (130, 'APPARTEMENT', 'T2', 13, 'SALON', 10000);
INSERT INTO BIEN VALUES (945, 'VILLA', 'MITOYENNE', 14, 'AIX-EN-PROVENCE', 250000);
INSERT INTO BIEN VALUES (150, 'VILLA', 'MITOYENNE', 15, 'LILE', 150000);
INSERT INTO BIEN VALUES (160, 'MAISON DE VILLE','T2', 16, 'MARSEILLE', 100000);
INSERT INTO BIEN VALUES (170, 'MAISON DE VILLE', 'T3', 17, 'LILE', 123000);
INSERT INTO BIEN VALUES (180, 'APPARTEMENT', 'STUDIO', 18, 'MARSEILLE', 12000);
INSERT INTO BIEN VALUES (190, 'MAISON DE VILLE', 'T3', 19, 'AIX-EN-PROVENCE', 125000);
INSERT INTO BIEN VALUES (200, 'APPARTEMENT', 'STUDIO', 20, 'LILE', 13000);

/*----------------------------------------------------------------------------*/
/*////////////////////////////////// ESPACE //////////////////////////////////*/
/*----------------------------------------------------------------------------*/

/*///////////////////////////////// TEMPLATE /////////////////////////////////*/
/* ----------------------------------------------------------------------------
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (00, '', 00.00, 00);
---------------------------------------------------------------------------- */

/* PUT THE TUPLE WHERE IDE START FROM 10 TO 110 */

/*120 - T3 - ~65 m² */
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (120,'MAISON BELCOURT',65.57,NULL);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1201,'SALON',24.17,120);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1202,'CHAMBRE 1',10.50,120);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1203,'CUISINE',15.25,120);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1204,'SALLE DE BAIN',15.65,120);
/*130 - T2 - ~45m² */
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (130,'T2MANS',45.00,NULL);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1301,'PIECE PRINCIPALE',30.00,130);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1302,'CHAMBRE 1',10.00,130);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1303,'SALLE DE BAIN',5.00,130);
/*945 - Villa - ~110 */
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (945,'VILLA DES SERIES POLICIERE',142.00,NULL);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (9451, 'EXTERIEUR', 50.00, 945);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (94511, 'JARDIN', 35.00, 9451);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (94512, 'PISCINE', 15.00, 9451);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (9452, 'BATIMENT', 60.00, 945);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (94521, 'SALON', 30.00, 9452);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (94522, 'CHAMBRE 1', 9.00, 9452);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (94523, 'CHAMBRE 2', 9.00, 9452);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (94524, 'CHAMBRE 3', 9.00, 9452);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (94525, 'CUISINE', 25.00, 9452);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (94526, 'BAIN', 10.00, 9452);
/*150 - VILLA - ~140 */
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (150,'VILLA LILE', 195.70,NULL);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1501,'EXTERIEUR', 60.50,150);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (15011,'JARDIN', 60.50,1501);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1502,'BATIMENT', 135.20,150);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (15021,'SALON', 46.00,1502);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (15022,'CHAMBRE 1', 19.17,1502);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (15023,'CHAMBRE 2', 20.03,1502);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (15024,'CHAMBRE 3', 20.50,1502);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (15025,'CUISINE', 15.00,1502);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (15026,'SALLE DE BAIN', 14.50,1502);
/*160 - T2 - ~45m² */
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (160,'MAISON ABSOLUMENT NORMALE',40.70,NULL);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1601,'SALON + CHAMBRE',20.00,160);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1602,'CUISINE',12.00,160);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1603,'SALLE DE BAIN',8.70,160);
/*170 - T3 - ~65m² */
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (170,'MAISON', 70.60, NULL);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1701,'SALON', 27.30, 170);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1702,'CHAMBRE', 13.15, 170);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1703,'CUISINE', 17.15, 170);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1704,'SALLE DE BAIN ',13.00, 170);
/* 180 - studion - ~20m² */
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (180,'STUDIO TOUT EST NORMALE', 180.00, NULL);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1801,'SALON + CUISINE + CHAMBRE', 147.63, 180);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1802,'SALLE DE BAIN NORMAL', 22.37, 180);
/* 190 - T3 MAISON DE VILLE */
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (190,'MAISON T3 DES MOR', 80.87, NULL);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1901,'SALON', 29.47, 190);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1902,'CHAMBRE ROUGE', 20.69, 190);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1903,'CUISISNE', 20.31, 190);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (1904,'SALLE DE BAIN', 10.40, 190);
/* 200 - STUDIO */
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (200,'STUDIO DU POIVRE', 16.70, NULL);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (2001,'SALON + CHAMBRE + CUISINE', 11.35, 200);
INSERT INTO ESPACE (IDE, DESIGNATION, SUPERFICIE, IDERATTACH) VALUES (2002,'SALLE DE BAIN', 5.35, 200);
